# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fm_pb2 as fm__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QnAStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetMode = channel.unary_unary(
                '/fm.QnA/SetMode',
                request_serializer=fm__pb2.SetModeRequest.SerializeToString,
                response_deserializer=fm__pb2.SetModeResponse.FromString,
                _registered_method=True)
        self.UploadDocument = channel.unary_unary(
                '/fm.QnA/UploadDocument',
                request_serializer=fm__pb2.UploadDocRequest.SerializeToString,
                response_deserializer=fm__pb2.UploadDocResponse.FromString,
                _registered_method=True)
        self.ListDocuments = channel.unary_unary(
                '/fm.QnA/ListDocuments',
                request_serializer=fm__pb2.ListDocsRequest.SerializeToString,
                response_deserializer=fm__pb2.ListDocsResponse.FromString,
                _registered_method=True)
        self.ClearDocuments = channel.unary_unary(
                '/fm.QnA/ClearDocuments',
                request_serializer=fm__pb2.ClearDocsRequest.SerializeToString,
                response_deserializer=fm__pb2.ClearDocsResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/fm.QnA/Query',
                request_serializer=fm__pb2.QueryRequest.SerializeToString,
                response_deserializer=fm__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.DirectQuery = channel.unary_unary(
                '/fm.QnA/DirectQuery',
                request_serializer=fm__pb2.QueryRequest.SerializeToString,
                response_deserializer=fm__pb2.QueryResponse.FromString,
                _registered_method=True)


class QnAServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DirectQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QnAServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=fm__pb2.SetModeRequest.FromString,
                    response_serializer=fm__pb2.SetModeResponse.SerializeToString,
            ),
            'UploadDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadDocument,
                    request_deserializer=fm__pb2.UploadDocRequest.FromString,
                    response_serializer=fm__pb2.UploadDocResponse.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=fm__pb2.ListDocsRequest.FromString,
                    response_serializer=fm__pb2.ListDocsResponse.SerializeToString,
            ),
            'ClearDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearDocuments,
                    request_deserializer=fm__pb2.ClearDocsRequest.FromString,
                    response_serializer=fm__pb2.ClearDocsResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=fm__pb2.QueryRequest.FromString,
                    response_serializer=fm__pb2.QueryResponse.SerializeToString,
            ),
            'DirectQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.DirectQuery,
                    request_deserializer=fm__pb2.QueryRequest.FromString,
                    response_serializer=fm__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fm.QnA', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fm.QnA', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QnA(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fm.QnA/SetMode',
            fm__pb2.SetModeRequest.SerializeToString,
            fm__pb2.SetModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fm.QnA/UploadDocument',
            fm__pb2.UploadDocRequest.SerializeToString,
            fm__pb2.UploadDocResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fm.QnA/ListDocuments',
            fm__pb2.ListDocsRequest.SerializeToString,
            fm__pb2.ListDocsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fm.QnA/ClearDocuments',
            fm__pb2.ClearDocsRequest.SerializeToString,
            fm__pb2.ClearDocsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fm.QnA/Query',
            fm__pb2.QueryRequest.SerializeToString,
            fm__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DirectQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fm.QnA/DirectQuery',
            fm__pb2.QueryRequest.SerializeToString,
            fm__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
