// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/fm.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QnA_UploadDocument_FullMethodName = "/qna.QnA/UploadDocument"
	QnA_Query_FullMethodName          = "/qna.QnA/Query"
)

// QnAClient is the client API for QnA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QnAClient interface {
	UploadDocument(ctx context.Context, in *UploadDocRequest, opts ...grpc.CallOption) (*UploadDocResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type qnAClient struct {
	cc grpc.ClientConnInterface
}

func NewQnAClient(cc grpc.ClientConnInterface) QnAClient {
	return &qnAClient{cc}
}

func (c *qnAClient) UploadDocument(ctx context.Context, in *UploadDocRequest, opts ...grpc.CallOption) (*UploadDocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadDocResponse)
	err := c.cc.Invoke(ctx, QnA_UploadDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qnAClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, QnA_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QnAServer is the server API for QnA service.
// All implementations must embed UnimplementedQnAServer
// for forward compatibility.
type QnAServer interface {
	UploadDocument(context.Context, *UploadDocRequest) (*UploadDocResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	mustEmbedUnimplementedQnAServer()
}

// UnimplementedQnAServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQnAServer struct{}

func (UnimplementedQnAServer) UploadDocument(context.Context, *UploadDocRequest) (*UploadDocResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadDocument not implemented")
}
func (UnimplementedQnAServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedQnAServer) mustEmbedUnimplementedQnAServer() {}
func (UnimplementedQnAServer) testEmbeddedByValue()             {}

// UnsafeQnAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QnAServer will
// result in compilation errors.
type UnsafeQnAServer interface {
	mustEmbedUnimplementedQnAServer()
}

func RegisterQnAServer(s grpc.ServiceRegistrar, srv QnAServer) {
	// If the following call pancis, it indicates UnimplementedQnAServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QnA_ServiceDesc, srv)
}

func _QnA_UploadDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QnAServer).UploadDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QnA_UploadDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QnAServer).UploadDocument(ctx, req.(*UploadDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QnA_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QnAServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QnA_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QnAServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QnA_ServiceDesc is the grpc.ServiceDesc for QnA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QnA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qna.QnA",
	HandlerType: (*QnAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadDocument",
			Handler:    _QnA_UploadDocument_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _QnA_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fm.proto",
}
